---
- name: Vérifier le système
  ansible.builtin.assert:
    that:
      - ansible_facts.distribution == "RedHat"
      - ansible_facts.distribution_major_version | int == 10

- name: Vérifier SELinux
  ansible.builtin.command: getenforce
  register: baseline_selinux
  changed_when: false

- name: Rapport SELinux
  ansible.builtin.debug:
    msg: "SELinux actuel={{ baseline_selinux.stdout }}"
