---
- name: Configurer chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: "0644"
    backup: "{{ backup_configs }}"
  notify: Restart chronyd
  when: hardening_mode == "enforce"

- name: Activer chronyd
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
    state: started
  when: hardening_mode == "enforce"
