---
- name: Déployer une politique sudo de base
  ansible.builtin.copy:
    dest: /etc/sudoers.d/99-hardening
    content: |
      Defaults use_pty
      Defaults logfile="/var/log/sudo.log"
    owner: root
    group: root
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
  when: hardening_mode == "enforce"
