  - name: Check if oracle file are present
    stat:
      path: "{{ item }}"
    register: oracle_files_exists
    with_items:
      - /wls
      - /apps/CA
      - /tibco

  - name: Check if /etc/ssh/sshd_config.d exists
    stat:
      path: /etc/ssh/sshd_config.d/
    register: _etc_ssh_sshd_config_d_exists

  - name: List /etc/sshd_config.d/*.conf files selection
    find:
      path: 
      - /etc/ssh/sshd_config.d/
      patterns: "*.conf"
    register: find_ssh_d_files
    when: _etc_ssh_sshd_config_d_exists.stat.isdir is defined and _etc_ssh_sshd_config_d_exists.stat.isdir

  - name: Verify if backup of files in /etc/ssh/sshd_config.d already exists
    stat:
      path: "{{ item.path }}.before_ssh_hardening.bkp"
    register: check_sshd_file_name
    with_items: "{{ find_ssh_d_files.files }}"
    when: _etc_ssh_sshd_config_d_exists.stat.isdir is defined and _etc_ssh_sshd_config_d_exists.stat.isdir

  - name: Verify if backup of /etc/ssh/sshd_config file already exist
    stat:
      path: /etc/ssh/sshd_config.before_ssh_hardening.bkp
    register: check_ssh_file

  - name: take backup of /etc/ssh/sshd_config file
    copy:
      src: "/etc/ssh/sshd_config"
      dest: "/etc/ssh/sshd_config.before_ssh_hardening.bkp"
      mode: preserve
      owner: root
      group: root
      remote_src: yes
    when: not check_ssh_file.stat.exists

  - block:
    - name: Take a backup of files /etc/ssh/sshd_config.d/*conf files
      copy:
        src: "{{ item.item.path }}"
        dest: "{{ item.item.path }}.before_ssh_hardening.bkp"
        mode: preserve
        owner: root
        group: root
        remote_src: yes
      with_items: 
        - "{{ check_sshd_file_name.results }}"
      when: not item.stat.exists
    when:
      - _etc_ssh_sshd_config_d_exists.stat.isdir is defined and _etc_ssh_sshd_config_d_exists.stat.isdir

  - name: Deduplicate parameters in /etc/ssh/sshd_config
    lineinfile:
      path: /etc/ssh/sshd_config
      create: false
      regexp: (?i)(?i)^\s*{{ item.key | regex_escape }}\s+
      state: absent
    with_items:
      - { key: GatewayPorts }
      - { key: PermitRootLogin }
      - { key: PermitEmptyPasswords }
      - { key: X11Forwarding }
      - { key: AllowTcpForwarding }
    notify: Restart sshd

  - name: Find sshd config files
    find:
      paths: /etc/ssh/sshd_config.d
      patterns: "*.conf"
    register: _etc_ssh_sshd_config_d_has_parameter

  - name: Remove parameters from /etc/ssh/sshd_config.d/*conf files
    lineinfile:
      path: "{{ item.0.path }}"
      regexp: (?i)(?i)^\s*{{ item.1 | regex_escape }}\s+
      state: absent
    loop: "{{ _etc_ssh_sshd_config_d_has_parameter.files | product(ssh_params) | list }}"
    vars:
      ssh_params:
        - GatewayPorts
        - PermitRootLogin
        - PermitEmptyPasswords
        - X11Forwarding
        - AllowTcpForwarding
    when: 
      - _etc_ssh_sshd_config_d_exists.stat.isdir is defined and _etc_ssh_sshd_config_d_exists.stat.isdir
    notify: Restart sshd  

  - name: Insert correct parameters in /etc/ssh/sshd_config.d/00-ssh-hardening.conf file
    lineinfile:
      path: /etc/ssh/sshd_config.d/00-ssh-hardening.conf
      create: true
      regexp: (?i)(?i)^\s*{{ item.key | regex_escape }}\s+
      line: "{{ item.key }} {{ item.value }}"
    with_items:
      - { key: GatewayPorts, value: '{{ var_GatewayPorts }}' }
      - { key: PermitRootLogin, value: '{{ var_PermitRootLogin }}' }
      - { key: PermitEmptyPasswords, value: '{{ var_PermitEmptyPasswords }}' }
      - { key: X11Forwarding, value: '{{ var_X11Forwarding }}'}
      - { key: AllowTcpForwarding, value: '{{ var_AllowTcpForwarding }}' }
    notify: Restart sshd 